In [21]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd 
from sklearn.model_selection import train_test_split

In [6]:
insurance_data = pd.read_csv("D:\desktop\Data Science Learning\Data-Science-learning\MachineLearning\DataSet\insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
gender_mapping = {
    "male" : 0,
    "female" : 1
}
# print(set(insurance_data["smoker"].values))
smoker_mapping = {
    "yes" : 1,
    "no" : 0
}
insurance_data["sex"] = insurance_data["sex"].map(gender_mapping)
insurance_data["smoker"] = insurance_data["smoker"].map(smoker_mapping)
insurance_data

      age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
X = insurance_data.drop(columns=["charges"])
Y = insurance_data["charges"]

## One hot encoding
X = pd.get_dummies(X, columns=["region"], drop_first=True, dtype=int)
X

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,0,0,1
1,18,0,33.770,1,0,0,1,0
2,28,0,33.000,3,0,0,1,0
3,33,0,22.705,0,0,1,0,0
4,32,0,28.880,0,0,1,0,0
...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,0,1,0,0
1334,18,1,31.920,0,0,0,0,0
1335,18,1,36.850,0,0,0,1,0
1336,21,1,25.800,0,0,0,0,1
1337,61,1,29.070,0,1,1,0,0

In [9]:
X["age_smoker"] = X["age"] * X["smoker"]
# print(X["age_smoker"].head())
X["bmi_smoker"] = X['bmi'] * X["smoker"]
X

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,0,0,1,19,27.90
1,18,0,33.770,1,0,0,1,0,0,0.00
2,28,0,33.000,3,0,0,1,0,0,0.00
3,33,0,22.705,0,0,1,0,0,0,0.00
4,32,0,28.880,0,0,1,0,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,0,1,0,0,0,0.00
1334,18,1,31.920,0,0,0,0,0,0,0.00
1335,18,1,36.850,0,0,0,1,0,0,0.00
1336,21,1,25.800,0,0,0,0,1,0,0.00
1337,61,1,29.070,0,1,1,0,0,61,29.07

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [23]:
lasso_model = Lasso(alpha=0.1)

lasso_model.fit(X_train, Y_train)

y_pred = lasso_model.predict(X_test)

mse = mean_squared_error(Y_test, y_pred)

r2 = r2_score(Y_test, y_pred)
r2

0.865236878283028

In [24]:
from sklearn.linear_model import LassoCV

alpha = [i for i in range(1, 100, 1)]

lasso_cv_model = LassoCV(
    alphas = alpha,
    cv = 5,
    max_iter=1000,
    random_state=42
)
lasso_cv_model.fit(X_train, Y_train)
print("best alpha: ", lasso_cv_model.alpha_)

y_pred = lasso_cv_model.predict(X_test)
mse = mean_squared_error(Y_test, y_pred)
print('Mse: ', mse)

r2 = r2_score(Y_test, y_pred)
r2

best alpha:  1
Mse:  20914832.63508914

0.8652817808292533